version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - GIT_URL_INSTEAD_OF: "https://github.com/=git@github.com:"
      - DOCKER_BUILDKIT: 1
    steps:
      - checkout
      - run: docker login --username vladaionescu --password "$DOCKERHUB_TOKEN"
      - run: docker build -t earthly/buildkit:`git branch --show-current` --target buildkit-buildkitd-linux .
      - run: echo docker push earthly/buildkit:`git branch --show-current`
